# Generated by Django 2.2.5 on 2020-12-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0002_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='productImages'),
        ),
    ]
