# Generated by Django 2.2.5 on 2020-12-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommend',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
