# Generated by Django 2.2.5 on 2020-12-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0009_auto_20201228_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
