# Generated by Django 2.2.5 on 2020-12-29 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProduct', '0011_color_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productImages')),
            ],
        ),
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.Color')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.Gender')),
                ('imageProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.ImageProduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.Size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
