# Generated by Django 2.2.5 on 2020-12-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0012_auto_20201229_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
