# Generated by Django 2.2.5 on 2020-12-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0014_auto_20201229_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='user',
        ),
    ]
