# Generated by Django 2.2.5 on 2020-12-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0015_remove_variants_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
