# Generated by Django 2.2.5 on 2020-12-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0017_remove_variants_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='variants',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProduct.Gender'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
