# Generated by Django 2.2.5 on 2020-12-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0018_auto_20201229_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
    ]
