# Generated by Django 2.2.5 on 2020-12-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0019_auto_20201229_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProduct.Color'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='imageProduct',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProduct.ImageProduct'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProduct.Size'),
        ),
    ]
