# Generated by Django 2.2.5 on 2020-12-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0020_auto_20201229_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='color',
        ),
        migrations.AddField(
            model_name='variants',
            name='color',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='appProduct.Color'),
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.AddField(
            model_name='variants',
            name='size',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='appProduct.Size'),
        ),
    ]
