# Generated by Django 2.2.5 on 2020-12-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0021_auto_20201230_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='imageProduct',
        ),
        migrations.AddField(
            model_name='variants',
            name='imageProduct',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='appProduct.ImageProduct'),
        ),
    ]
