# Generated by Django 2.2.5 on 2020-12-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0023_imageproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='quantity',
        ),
    ]
