# Generated by Django 2.2.5 on 2020-12-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0024_auto_20201231_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProduct.Gender'),
        ),
    ]
