# Generated by Django 2.2.5 on 2020-12-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0010_auto_20201228_1703'),
        ('order', '0002_auto_20201228_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProduct.Gender'),
        ),
    ]
