# Generated by Django 2.2.5 on 2021-01-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210102_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
