# Generated by Django 2.2.5 on 2021-01-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210102_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='toltalquantity',
        ),
    ]
