# Generated by Django 2.2.5 on 2021-01-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_cart_toltalquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
